analysis_options.yaml
example/.gitignore
example/analysis_options.yaml
lib/src/Config.dart
lib/src/Constants.dart
lib/src/Dialog.dart
lib/src/Dialog/RequestSender.dart
lib/src/DigestAuthentication.dart
lib/src/Message.dart
lib/src/Parser.dart
lib/src/RTCSession.dart
lib/src/RTCSession/DTMF.dart
lib/src/RTCSession/Info.dart
lib/src/RTCSession/ReferNotifier.dart
lib/src/RTCSession/ReferSubscriber.dart
lib/src/Registrator.dart
lib/src/RequestSender.dart
lib/src/SIPMessage.dart
lib/src/Transactions.dart
lib/src/Transport.dart
lib/src/UA.dart
lib/src/grammar_parser.dart
lib/src/sanityCheck.dart
test/test_digest_authentication.dart

This pull request refactors the Sip Method from a String to an Enum and infers types where possible which should ease the long term maintenance of the project.
Included are a few bug fixes, namely 
* the use of Slice() is SIPMessage.dart
* fix for Exception in Parser.dart

Refactor sip method and some bug fixes

---

lib/src/RTCSession.dart

I added state storage to flutter-webrtc.
https://github.com/cloudwebrtc/flutter-webrtc/commit/396af855ac7f13a378c4dcd87856e60dfdfeb7a2
Try to fix the error after receiving 180/183 with SDP.

Reset signalling state when answer a call after receiving 180/183 with SDP.

---

README.md
example/analysis_options.yaml
example/lib/main.dart
example/lib/src/callscreen.dart
example/lib/src/dialpad.dart
example/lib/src/register.dart
example/lib/src/sip_ua_helper.dart
example/test/test2_websocket.dart
lib/src/Config.dart
lib/src/Dialog.dart
lib/src/Dialog/RequestSender.dart
lib/src/Grammar.dart
lib/src/Message.dart
lib/src/Parser.dart
lib/src/RTCSession.dart
lib/src/RTCSession/ReferSubscriber.dart
lib/src/Registrator.dart
lib/src/RequestSender.dart
lib/src/SIPMessage.dart
lib/src/Transport.dart
lib/src/UA.dart
lib/src/WebSocketInterface.dart
lib/src/sanityCheck.dart
lib/src/transactions/Transactions.dart
lib/src/transactions/ack_client.dart
lib/src/transactions/invite_client.dart
lib/src/transactions/invite_server.dart
lib/src/transactions/non_invite_client.dart
lib/src/transactions/non_invite_server.dart
lib/src/transactions/transaction_base.dart

Fixed a number of merge issues from the prior PR.
Set the analyzer to "string-mode" for the example project and cleaned up resulting warnings.
also a few bug fixes

Clean up example and resolve merge issues

---

example/lib/main.dart
example/lib/src/callscreen.dart
example/lib/src/dialpad.dart
example/lib/src/register.dart
lib/sip_ua.dart
lib/src/Config.dart
lib/src/Dialog.dart
lib/src/Dialog/RequestSender.dart
lib/src/Message.dart
lib/src/Parser.dart
lib/src/RTCSession.dart
lib/src/Registrator.dart
lib/src/RequestSender.dart
lib/src/SIPMessage.dart
lib/src/UA.dart
lib/src/enum_helper.dart
lib/src/event_manager/event_manager.dart
lib/src/event_manager/events.dart
lib/src/sanityCheck.dart
lib/src/sip_ua_helper.dart
lib/src/transactions/ack_client.dart
lib/src/transactions/invite_client.dart
lib/src/transactions/invite_server.dart
lib/src/transactions/non_invite_client.dart
lib/src/transactions/non_invite_server.dart
lib/src/transactions/transaction_base.dart
pubspec.yaml
test/test_sip_ua.dart

I've divided this PR into 2 commits. Although neither commit is viable without the other, it helps to separate the simple and complex parts of this PR.
The first commit https://github.com/cloudwebrtc/dart-sip-ua/commit/acdba147f83f6f5a610d90af4630f2b79a879e9f simply changes paths and imports
The second commit https://github.com/cloudwebrtc/dart-sip-ua/commit/e0c474cf9f88f4cfa2e822ac62d151ae39374a81 is concerned with changing the listener mechanism between example and sip_ua_helper

Move sip_ua and hide internals

---

lib/src/Config.dart
lib/src/Dialog.dart
lib/src/Parser.dart
lib/src/RTCSession.dart
lib/src/SIPMessage.dart
lib/src/UA.dart
lib/src/WebSocketInterface.dart
lib/src/event_manager/events.dart
lib/src/logger.dart
lib/src/sip_ua_helper.dart
lib/src/transactions/invite_client.dart
lib/src/transactions/invite_server.dart
lib/src/transactions/non_invite_client.dart
lib/src/transactions/non_invite_server.dart
lib/src/transactions/transaction_base.dart

Add control over the logging level, default is still debug. 
SIPUPHelper now has a setter for loggingLevel
If a logger call is below the set Level, then the log output will be suppressed.
Improved error messages when attempting to connect and register.
Inferred more type information.
adjusted some logging levels from debug to info

Types and logs pr

---

example/lib/main.dart
example/lib/src/callscreen.dart
example/lib/src/utils/dart_html_dummy.dart
example/lib/src/utils/key_value_store.dart
example/lib/src/utils/key_value_store_web.dart
lib/src/dialog.dart
lib/src/logger.dart
lib/src/web_socket_dummy.dart
lib/src/websocket_interface.dart
lib/src/websocket_web_impl.dart

Merry Christmas and a Happy new year, I've been busy with another project for a while.
The dart:html (and others) import were causing compile errors for the flutter environment.
I've added conditional imports and alternative non-functional dummy classes to enable a clean compile.
There are also a few minor formatting and syntax changes to address some compile warnings and errors.
and finally a small fix for the logger.

fix for dart:html import and related errors

---

README.md

Quickstart for those who know nothing about Flutter

Quickstart

---

lib/src/config.dart
lib/src/ua.dart

The global instance of `Settings` in `lib/src/config.dart` causes different UA instances to share settings, meaning that e.g. all instances try to auth with the same credentials even if initialised with different creds. This solves that by creating a new `Settings` instance for each UA.

Prevent sharing of config between different UA instances

---

lib/src/sip_ua_helper.dart

Add iceServers param. With custom STUN and TURN server, I was able to fix this issue #79

Able to change iceServers

---

example/lib/src/callscreen.dart
example/lib/src/dialpad.dart
example/lib/src/register.dart
lib/src/event_manager/event_manager.dart
lib/src/event_manager/internal_events.dart
lib/src/event_manager/message_events.dart
lib/src/message.dart
lib/src/parser.dart
lib/src/sip_message.dart
lib/src/sip_ua_helper.dart
lib/src/ua.dart

Add support listening to incoming SIP text message
- Move EventNewMessage from internal event as export event type to be used.
- Add a new override function void onNewMessage(SIPMessageRequest msg) to interface. User should process the new incoming text message in this function.
- Fix the problem that content length of SIP message was not calculated correctly when UTF-8 characters were met.
- Modify the example to show the incoming text message on dial pad screen.
In the new example, send text message to registed client of the SIP UA, the message will be shown on dial pad screen. And the code handling incoming message looks like below in dialpad.dart.
void onNewMessage(SIPMessageRequest msg) {
//Save the incoming message to DB
String msgBody = msg.request.body as String;
setState(() { …

Add SIP message listener to listen the new incoming SIP text message

---

lib/src/sip_ua_helper.dart

Asserting !registered on unregister doesn't make sense, instead if we want to UNREGISTER we want to make sure we are REGISTERED

Fix incorrect register assert

---

lib/src/sip_ua_helper.dart

Related to my feature request #153, I have added the DTMF options to the method in Call. 
It should be an optional parameter, however, I couldn't use the flutter tests to verify that all functionality still works as expected, as I am missing the required SIP server locally.

Add dtmf options from RTCSession to Call

---

example/lib/src/callscreen.dart

Hi there, 
When I run the sample app on Android 9. 
If I confirm a call with https://tryit.jssip.net, the `Speaker On` is not activated while sound is actually coming from speakers.. 
I ve not tested on iOS. 
So here is a PR... 
Regards and thank you for your great work guys

:bug: makes sure speaker is off to match UI state

---

lib/src/sip_ua_helper.dart

The method `buildCallOptions` was already there but not used and instead `_options` was used directly so that I cannot override the default options by extending the SIPUAHelper class in a custom class and use the custom class instead.
This will affect #169 as the `sdpSemantics` property cannot be set currently. After this merge we can modify the `pcConfig` key-value pair in the options map returned from `buildCallOptions`.

Let the user override the call options by extending SIPUAHelper

---

lib/src/sip_ua_helper.dart
lib/src/transports/websocket_interface.dart

I know this is kind of a crazy change as it lets the user configure the `via_transport` String used.
But we have the problem that we have a server that is using an URL prefixed with `wss://` but expecting `VIA SIP/2.0/WS` instead of `VIA SIP/2.0/WSS`.
So I figured it would not hurt if the user would be able to customize it.

Configuring via_transport

---

lib/src/rtc_session.dart

Hi there me again!
We found out that now with `unified-plan` mute wasn't working anymore as there were no streams added to `_connection.getLocalStreams()` as we only call `addTrack`.
As we only have one stream called `_localMediaStream` in the `RTCSession` we thought it might make sense to just use that one for muting. Is that ok or do you have doubts?

Fixed mute audio for unified-plan

---

pubspec.yaml

need to get around this error
`sip_ua depends on crypto ^2.1.2 and universal_io >=2.0.0 depends on crypto ^3.0.0`
tested and working with camera too.

bump dependencies

---

lib/src/sip_ua_helper.dart

Fix for https://github.com/flutter-webrtc/dart-sip-ua/issues/185

Expose sendInfo from RTCSession to Call.sendInfo

---

lib/src/rtc_session.dart

**Problem**:
If session has been terminated during setTimeout for `ready` function that `function` will throw an exception `NoSuchMethodError: The setter 'onIceCandidate=' was called on null.`. That happens because by that time `_connection` is `null` and we try to access `onIceCandidate` on it. The issue itself doesn't cause any problems besides an uncaught error.
**How to reproduce the issue:**
- make a phone call to an app using dart-sip-ua
- accept the call
- hang up the call on the caller side in the first 3 seconds after the call has been accepted
**Fix description**
I've just added a check inside `ready` function to check if session has been terminated. May be a better fix would be to store `ready` function on `rtc_session` and clear timer during session `close()`. What do you …

Don't run ready function if session has been terminated

---

lib/src/grammar.peg
lib/src/grammar_parser.dart
lib/src/parser.dart

Using Unicode characters represented with more than 1 byte in utf8 would cause parsing problems. The parser would convert string to array of Unicode (32-bit) units, but the grammar is inherently utf8 (8-bit) based.
- Update *grammar.peg* to mirror RFC
- Update index used in body extraction when parsing (UTF8,16,32 inconsistencies)
- Modify *_text* and *_toCodePoints* of generated *grammar_parser.dart* so parser consistently use UTF8
Take these rules:
```peg
quoted-string  =  SWS DQUOTE *(qdtext / quoted-pair ) DQUOTE
quoted_pair <- "\\" ( [\x00-\x09] / [\x0B-\x0C] / [\x0E-\x7F] )
qdtext =  LWS / %x21 / %x23-5B / %x5D-7E / UTF8-NONASCII
UTF8_NONASCII   <- [\u0080-\uFFFF]
```
With a from header:
```
From: "𤭢" <sip:user@site.com>;tag=asdfqwerty
```
𤭢
UTF8: 0xF0 0xA4 0xAD 0xA2
UTF16: 0xD852 …

Parser fix

---

lib/src/rtc_session.dart
lib/src/transactions/invite_client.dart
lib/src/ua.dart

For further detail look into #282.
This also fixes a problem where when cancelling a phone call in the initiation stage would lead to an error, because cancel_reason would not yet be set. Now the default reason is OK

Fix bug where stopping the SIPUAHelper caused a ConcurrentModificationError. Closes #282

---

pubspec.yaml

Fix in 0.9.9: [Android] Support rtp transceiver direction type 4.

Update flutter_webrtc  to 0.9.9

---

lib/src/sip_ua_helper.dart

When using digest authentication with a stored ha1, the UA is requiring the realm to be also set.

Add realm option to SIPUAHelper settings

---

lib/src/config.dart
lib/src/rtc_session.dart

The default timeout of 500ms for gathering ice candidates can be too short in some cases. 
This change allows setting a different value or disabling the timeout.

Allow setting ice_gathering_timeout option

---

lib/src/config.dart
lib/src/sip_ua_helper.dart
lib/src/transports/websocket_dart_impl.dart
lib/src/transports/websocket_interface.dart

After INVITE from an app, server sends proxy-authorization challenge and app sends ACK and INVITE with proxy-authorization. However sometimes the Server doesn't recieve the second invite(It recieves the ACK tho). The delay fixes this issue, possibly because server needs delay between these two messages.

Websocket message queue using streams and Delay between messages

---

lib/src/sip_message.dart

Should fix the issue of not being able to hang up on an incoming call.: close https://github.com/flutter-webrtc/dart-sip-ua/issues/255

fix(hangup): set cancel reason nullable

---

lib/src/sip_ua_helper.dart

Because the return value of start is void rather than Future<void> it is impossible to await it's completion because it has been flagged as async.
Users choosing to allow the call to be completed asynchronously can simply ignore the Future<void> but those wanting to act after registration is complete cannot do so without this change.

Allow await on helper start call

---

lib/src/event_manager/call_events.dart
lib/src/rtc_session.dart
lib/src/sip_ua_helper.dart

Sometimes we want to check whether the "progress" event has early media (183 Session Progress) or not (180 Ringing) to controll a ring back tone playback. This change will provide the status code via CallState.cause.

Add status code to CallState on the progress event

---

lib/src/rtc_session.dart

Hello,
the goal for this PR is to provide everything we need to to an attended transfer, which we're not able to do right now.
The sessions refer method exposes an `option` parameter where we can set the `replaces`-headers.
Right now we can't access the sessions to_tag and from_tag which are required in the replaces header to do an attended transfer.
For now I would suggest to expose the to_tag and from_tag only. 
This would provide the necessary information for an attended transfer and gives us freedom to implement the attended transfer ourself.
Related issues:
- https://github.com/flutter-webrtc/dart-sip-ua/issues/364
- https://github.com/flutter-webrtc/dart-sip-ua/issues/198

expose rtc_session to/from-tag

---

lib/src/rtc_session.dart

This change will allow user to control the DTMF sending interval by `sendInterval` option.
For users who are using SIP INFO DTMF, waiting the period `duration + interToneGap` is not nessesary.

Add sendInterval to dtmf

---

lib/src/ua.dart

Seems we found an issue in case of using WSS transport. In that case 'Contact' header contains 'ws' value instead of 'wss'. 
```Contact: <sip:lovxxb@k87kr43mm.invalid;transport=WS;ob>```
It leads to call issue: 'Failed to set remote offer sdp: Called with SDP without DTLS fingerprint'
We suppose it is regression after implementation TransportType.  Previously transport initialized using socket via_transport value ( ws | wss, depends on transport ). Currently it initializes using just TransportType enum value (ws, tcp), which does not cover the wss usage scenario.
https://github.com/flutter-webrtc/dart-sip-ua/commit/024d0e847dba866e7ff80ce1c518091fe0e7496c#diff-28c3dd474c00b015a64df65906a721293e92dba454e56886f0cb3de9701baf96L856-L861

Set transport value using socket via_transport 

---

example/lib/main.dart
example/lib/src/callscreen.dart
example/lib/src/dialpad.dart
example/lib/src/register.dart
example/lib/src/theme_provider.dart
example/lib/src/widgets/action_button.dart
example/pubspec.yaml
lib/src/config.dart
lib/src/event_manager/internal_events.dart
lib/src/parser.dart
lib/src/rtc_session.dart
lib/src/sip_message.dart
lib/src/sip_ua_helper.dart
lib/src/socket_transport.dart
lib/src/ua.dart

Had to make an adjustment on the first PR, then it started failing some formatter check, hopefully this one cleanly passes the checks.
Added the infrastructure to be able to upgrade a voice call to a video call. This introduced a new listener function to override 'onNewReinvite(ReInvite event)' which is used by the app that uses the package so it can handle the UI for the upgrade request. Also updated the example app to use the upgrade to video functionality.
Added darkmode to the example app.
Refactored how the call screen detects whether it is a voiceOnly call. Previously you could make a video call and the remote side would be told its an audio call. Only when they accept are they suprised to see its a video call. Now on an incoming call it detects if remote has video and for an …

Upgrade to video call implementation and dark mode 2

---

lib/sip_ua.dart
lib/src/rtc_session.dart

Allows to set custom from_uri & from_display_name for call operation using customOptions parameter.
```
Future<void> initiateCall(String target) async {
Map<String, String> customOptions = {};
var currentCallerId = '186455555'
customOptions['from_uri'] =
URI('sip', currentCallerId, _config.domain).toString();
customOptions['from_display_name'] = 'User Name'
var mediaStream = await navigator.mediaDevices.getUserMedia(
_mediaConstraints);
_helper.call(target, voiceonly: true,
mediaStream: mediaStream,
customOptions: customOptions);
}
```
**From: "User Name" <sip:186455555@sip.x.systems>;tag=52rmnxgcmt**

Uri configuration for call operation

---

lib/src/sip_ua_helper.dart
lib/src/ua.dart

* allows to change `uri` configuration parameter for `UA` without instance reload
* allows to set `UA` dynamic parameters from `SIPUAHelper`
useful to set `From` header display name and URI parts before the call.
example:
```
sip_ua_helper = SIPUAHelper();
...
sip_ua_helper.setUAParam('display_name','test');
sip_ua_helper.setUAParam('uri', URI('sip','42','domain.invalid'));
sip_ua_helper.call(target);
```

allow to change UA uri in runtime

---

example/lib/src/callscreen.dart
example/lib/src/register.dart
example/test/widget_test.dart
lib/src/rtc_session.dart
lib/src/sip_ua_helper.dart

Where as before i was using _sendReinvite() for the video upgrade, the video upgrade logic was interfering with the hold logic. Now i have reverted _sendReinvite() back to how it was and introduced a new _sendVideoUpgrade() for a seperation of concern. 
Tested on a FreePBX server that hold is now working. Also to note a few people have said the other side doesnt get notified if they're put on hold. This actually does work with this package but their problem is a PBX problem specifically they havent set moh_passthrough = yes on their endpoints. With that configuration I observer the other side displaying that they had been put on hold by the remote.
This also fixed  #492 where event handlers were unneccesarily being introduced.
and #473 with the hold get media types error.

Hold and video upgrade fixed

---

lib/src/ua.dart

Hey there! 
Sometimes I am getting a bug like this:
```
Concurrent modification during iteration: _Map len:1.
StackTrace: #0      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:635)
#1      UA.stop (package:sip_ua/src/ua.dart:325)
```
I was wondering what causes the bug and found that there is a case when call is stopping but package is trying to destroy session in sessions list at the same time. I saw that you have `_stopping` flag already in your `stop` function and use it to prevent list modifications if they can cause an error. So I taught that I can use that flag to fix my problem. 
Seems like I am not getting this error any more :)

Concurrent modification during iteration bug fix
